### PR TITLE
feat: add svelte and react support

### LINKED ISSUE #106: feat: add `svelte` support
Add `svelte` virtual module similar to `vue` virtual module `virtual:pwa-register/vue`.

### LINKED ISSUE #108: feat: add `react` support
Add `react` virtual module similar to `vue` virtual module `virtual:pwa-register/vue`.

### PR DESCRIPTION
**Pull request by userquin**
This PR include:
- virtual module for `svelte`: `virtual:pwa-register/svelte`
- `svelte-basic` example: with prompt for update
- `svelte-routify` example: with `routify` router, with prompt for update and auto update; with configurable periodic sw update for both register types

closes #106
closes #108

### CODE REVIEW

**Comment by userquin** [comment]
To run the examples (first build the plugin `pnpm install && pnpm run build`):
- `svelte-basic`: `pnpm run example:svelte:start`
- `svlete-routify`: prompt for update with no check for sw updates: `pnpm run example:svelte:routify:start`
- `svlete-routify`: auto update with no check for sw updates: `pnpm run example:svelte:routify:start:claims`
- `svlete-routify`: prompt for update with check for sw update: `pnpm run example:svelte:routify:start:reloadsw`
- `svlete-routify`: auto update with check for sw update: `pnpm run example:svelte:routify:start:claims:reloadsw`

Remember, for last 2 examples (check for sw update) you must wait 1 minute between registrations.

**Comment by antfu** [comment]
At some point, I guess we need a prompt script for the more and more complex demo scripts 😅

**Comment by userquin** [comment]
> 
> 
> At some point, I guess we need a script to prompt for the more and more complex demo scripts 😅

We will need some plugin to name the scripts...

**Comment by userquin** [comment]
I'll add some description for the command scripts.

**Comment by userquin** [comment]
The scripts on previous comment are wrong for last 4 scripts, should start with `svelte` (wording). The scripts command are ok on `package.json`, I'll updated the comment.

**Comment by userquin** [comment]
I'll also include here `react` support, don't merge yet.

**Comment by userquin** [comment]
About `react` this PR will include:
- virtual module for `react`: `virtual:pwa-register/react`
- `react-basic` example: with prompt for update
- `react-router` example: with `react-router-dom` router, with prompt for update and auto update; with configurable periodic sw update for both register types

**Comment by userquin** [comment]
To run the react examples (first build the plugin pnpm install && pnpm run build):

- react-basic: pnpm run example:react:start
- react-router: prompt for update with no check for sw updates: pnpm run example:react:router:start
- react-router: auto update with no check for sw updates: pnpm run example:react:router:start:claims
- react-router: prompt for update with check for sw update: pnpm run example:react:router:start:reloadsw
- react-router: auto update with check for sw update: pnpm run example:react:router:start:claims:reloadsw

Remember, for last 2 examples (check for sw update) you must wait 1 minute between registrations.

**Comment by userquin** [comment]
@antfu review `src/client/build/react.ts` I think the states can be simplified

**Comment by dheimoz** [comment]
@userquin you are on fire!!!!!!

**Pull request merged**
