### PR TITLE
feat: add `SolidJS` support

### LINKED ISSUE #141: add `SolidJS` support
I have it on local also the pwa docs, I only need to add the 3 examples...

### PR DESCRIPTION
**Pull request by userquin**
closes #141

### CODE REVIEW

**Comment by antfu** [comment]
I appreciate the hard work - but do we really need that many examples? 😅 I am worried about having too much code and duplications will make the future maintainability barrier.

**Comment by userquin** [comment]
@antfu ready to review again, I'm still getting some `__VP_STATIC_START__`: see https://github.com/vuejs/vitepress/issues/420

Maybe I can bump vitepress to use latest `0.20.0` before merge this PR.

imagen

**Comment by userquin** [comment]
To run the `solid-router` examples (first build the plugin `pnpm install && pnpm run build`), from the root folder:

- `injectManifest` with ready to work offline and prompt for update `pnpm run example:solid:router:start:sw`
- `generateSW` with prompt for update with no check for sw updates: `pnpm run example:solid:router:start`
- `generateSW` with auto update with no check for sw updates: `pnpm run example:solid:router:start:claims`
- `generateSW` with prompt for update with check for sw update: `pnpm run example:solid:router:start:reloadsw`
- `generateSW` with auto update with check for sw update: pnpm run `example:solid:router:start:claims:reloadsw`

Remember, for last 2 examples (check for sw update) you must wait 1 minute between registrations.

**Comment by userquin** [comment]
Due to the ammount of things to change (solid and preact support, doc changes, update deps), I'll close it, a new one PR from this repo will supersede this PR.

@antfu the solid support and the example for it, is just a copy/paste of the PR in my repo, so feel free to review if you want.

The new PR from the new branch here will be on draft until I add all the changes on docs.

**Pull request closed without merging**
